[package]
name = "wterm"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "^0.32"
egui = "^0.32"
vte = "^0.15"
portable-pty = "^0.9.0"
anyhow = "1.0"
unicode-width = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
raw-window-handle = "0.6"
